[project]
<<<<<<< HEAD
name = "nonebot_plugin_sparkapi"
version = "2.0.4"
description = "Nonebot2 ChatBot that calls the official API of the iflyrec SparkDesk for all model versions, defaulting to the current latest (v4.0)"
authors = [
    { name = "CCLMSY", email = "2502408581@qq.com" }
]
dependencies = [
    "nonebot-adapter-onebot >=2.2.1, <3.0.0",
    "nonebot2 >=2.0.0rc3, <3.0.0",
    "websockets >=12.0, <13.0",
    "httpx >=0.19.0, <1.0.0",
    "pillow >=10.0.0, <11.0.0",
]
requires-python = ">=3.10"
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

=======
<<<<<<< HEAD
name = "nonebot-plugin-sparkapi"
version = "3.0.0"
description = "Nonebot2 plugin that calls the official API of the iflyrec SparkDesk"
authors = [
    {name = "CCLMSY", email = "2502408581@qq.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}
=======
name = "nonebot_plugin_sparkapi"
version = "2.0.9"
description = "Nonebot2 plugin that calls the official API of the iflyrec SparkDesk for all model versions, defaulting to the current latest"
authors = [{ name = "CCLMSY", email = "2502408581@qq.com" }]
dependencies = [
    "nonebot2>=2.3.3",
    "httpx>=0.27.0",
    "websockets>=12.0",
    "nonebot-plugin-alconna>=0.51.4",
    "nonebot-plugin-localstore>=0.6.0,<1.0.0",
    "nonebot-plugin-session>=0.3.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
>>>>>>> main

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
<<<<<<< HEAD
=======

[tool.pdm.dev-dependencies]
dev = [
    "nonebot2[fastapi]>=2.3.3",
    "nonebot-adapter-onebot>=2.4.4",
]

[tool.nonebot]
plugins = ["nonebot_plugin_alconna", "nonebot_plugin_localstore", "nonebot_plugin_session"]
>>>>>>> main
>>>>>>> beta
